### ISSUE TITLE
XY Plot: Support changing a parameter with two chained Sampler nodes?

### ISSUE THREAD

**Issue by alexopus** [LucianoCirino/efficiency-nodes-comfyui#100]
With XY Plot, is there a way to change the parameters in two chained samplers?
For example in the image below I am trying to have 8 resulting images, for "dpmpp_2m_sde; dpmpp_2m_sde_gpu; dpmpp_3m_sde; dpmpp_3m_sde_gpu;" x "karras; exponential;", but that would go through first sampler and an upscaling one:
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/25933468/92f4c1fb-d3a0-4c5b-b9f6-dc25cb81aebf)

I tried simply passing the script to both, but then first sampler does what is expected, but second one applies the changes only to the first input image of the 8. Where I would like first X,Y combo applied to first image, second to second, and so on.

Is it possible?

**Comment by LucianoCirino** [comment]
Its not possible right now, but I like the idea and would like to implement it. I believe this is the same question asked on this issue ->https://github.com/LucianoCirino/efficiency-nodes-comfyui/issues/52

So would each input image generate its own plot? so in your example it would result in 8 plots from second sampler?

**Comment by alexopus** [comment]
In this particular example, at the end I would like to have one plot with 8 images, where each image went through two samplers (with an upscale in between - forgot to include that part of the graph in the screenshot) with matching settings:

```
image 1: 1st sampler "dpmpp_2m_sde & karras"          -> 2nd sampler "dpmpp_2m_sde & karras";
image 2: 1st sampler "dpmpp_2m_sde_gpu & karras"      -> 2nd sampler "dpmpp_2m_sde_gpu & karras";
image 3: 1st sampler "dpmpp_3m_sde & karras"          -> 2nd sampler "dpmpp_3m_sde & karras";
image 4: 1st sampler "dpmpp_3m_sde_gpu & karras"      -> 2nd sampler "dpmpp_3m_sde_gpu & karras";
image 5: 1st sampler "dpmpp_2m_sde & exponential"     -> 2nd sampler "dpmpp_2m_sde & exponential";
image 6: 1st sampler "dpmpp_2m_sde_gpu & exponential" -> 2nd sampler "dpmpp_2m_sde_gpu & exponential";
image 7: 1st sampler "dpmpp_3m_sde & exponential"     -> 2nd sampler "dpmpp_3m_sde & exponential";
image 7: 1st sampler "dpmpp_3m_sde_gpu & exponential" -> 2nd sampler "dpmpp_3m_sde_gpu & exponential";
```

In a way, this would be similar to what a1111 does when you enable hires fix and use X/Y/Z plot - settings are applied to both first sampler and "hires" sampler.

> So would each input image generate its own plot? so in your example it would result in 8 plots from second sampler?

No, not 8 plots per each of the 8 input images as you suggest, although that may be still something one might want in a different scenario. This is maybe easier to implement, by allowing handling of image sets as input and maybe two different sets of XYPlot nodes? Perhaps that is even already possible now?

**Comment by LucianoCirino** [comment]
So if I understood correctly...You are basically doing an XY PLot but with a Latent Upscale applied to each image as a sort of post processing before setting it down on the plot. Will have to think about this one a little more carefully.

**Comment by LucianoCirino** [comment]
This is now possible via the HiRes Fix Script node
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/daae3b2c-986d-4f99-ac16-3d08d15f37ff" width="720">

**Comment by alexopus** [comment]
Very nice, I'll give it a try soon!

**Comment by alexopus** [comment]
It is working as expected. thanks!
