### ISSUE TITLE
I hope to add support for CLIP skip in XY Plot

### ISSUE THREAD

**Issue by Yorha4D** [LucianoCirino/efficiency-nodes-comfyui#11]
@LucianoCirino It's really convenient to use it, but there are still some areas where it can be improved. For example, I hope to add support for CLIP skip in XY Plot
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/116185401/56bb4902-ab67-48f7-9e6a-6a8e9e130efa)

**Comment by LucianoCirino** [comment]
Does the new XY Plot Checkpoint Input Node meet your needs?

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/ac04cca3-b099-4e74-b2e2-598695948c2e)

Only thing is I am not showing the clip_skip value on the plot results for aesthetic reasons.

**Comment by Yorha4D** [comment]
It's really cool, the problem has been solved~
