### ISSUE TITLE
name 'model_lora_keys_unet' is not defined

### ISSUE THREAD

**Issue by qeoakes** [LucianoCirino/efficiency-nodes-comfyui#110]
Stack trace:

```
Error occurred when executing Efficient Loader:

name 'model_lora_keys_unet' is not defined

File "H:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "H:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "H:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "H:\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 101, in efficientloader
model, clip = load_lora(lora_params, ckpt_name, my_unique_id, cache=lora_cache, ckpt_cache=ckpt_cache, cache_overwrite=True)
File "H:\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 319, in load_lora
lora_model, lora_clip = recursive_load_lora(lora_params, ckpt, clip, id, ckpt_cache, cache_overwrite, folder_paths)
File "H:\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 310, in recursive_load_lora
lora_model, lora_clip = load_lora_for_models_tsc(ckpt, clip, lora_path, strength_model, strength_clip)
File "H:\comfyui\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_sd.py", line 122, in load_lora_for_models_tsc
key_map = model_lora_keys_unet(model.model)
```

Steps to recreate:
Run ComfyUI commit f72780a (current).
Load a lora with Efficient Loader, XY Input: LoRA, or XY Manual Entry with LoRA option. Just tested and even occurs with Lora Stacker into Efficient Loader with no XY.
Hit Generate.

I didn't save my workflow that was functional before the recent commit, but I've just thrown this one together to recreate the issue. If I'm using these nodes in error, please let me know and feel free to close the issue.
[model_lora_keys_unet.zip](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12445557/model_lora_keys_unet.zip)

**Comment by qeoakes** [comment]
Looks like it may be related to a refactor of mainline comfyui with lora.py 17 hours ago as of now.

**Comment by LucianoCirino** [comment]
Please use the repo version of 'Efficiency Nodes' and not the Civit AI version. Stay up to date by using the [ComfyUI Manager](https://github.com/ltdrdata/ComfyUI-Manager).

**Comment by qeoakes** [comment]
I do use that one? It's not pulling an update. I'll uninstall and reinstall. Thank you.

**Comment by qeoakes** [comment]
That did the trick, thank you!
