### ISSUE TITLE
XY Plot Manual Entry disappeared

### ISSUE THREAD

**Issue by alessandroperilli** [LucianoCirino/efficiency-nodes-comfyui#117]
The latest git pull brought in a surprise: both the XY Manual Entry node and the XY Manual Entry Info are gone. 

They were the most powerful and flexible way to instruct an XY Plot, especially for a complex search & replace comparison. Is this permanent? Or do you plan to bring them back?

Thank you

**Comment by LucianoCirino** [comment]
The nodes are simply disabled right now because its broken with all the changes I have made. They will be brought back soon friend.

**Comment by alessandroperilli** [comment]
You truly have. I spent the last 4h to redo my workflow because of the crippling changes. The positive is that your new implementation massively simplifies the wiring.

**Comment by LucianoCirino** [comment]
Node has been put back!

**Comment by Unstable-Reality** [comment]
Amazing, thank you.

**Comment by alessandroperilli** [comment]
Wonderful, thank you.
