### ISSUE TITLE
'ModelPatcher' object is not iterable when connecting SDXL Tuple to other nodes

### ISSUE THREAD

**Issue by alessandroperilli** [LucianoCirino/efficiency-nodes-comfyui#121]
Not 100% sure this is related to the latest round of changes, but now I have the situation captured in the screenshot:

<img width="789" alt="Screenshot 2023-08-31 at 12 51 31" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/5ae838bc-6f7a-42f9-82ea-0997d1a646e9">

Which generates the following error:

`'ModelPatcher' object is not iterable`

I used a different pipe node to send the variables to the `Ultimate SD Upscale` node and never had a problem. Now that I'm using the SDXL Tuple pipe, I get this and it cannot complete the operation.

I have the same problem when I connect the SDXL Tuple to `ConditioningZeroOut` and `DetailerDebug SEGS` nodes.

Any help would be appreciated.

**Comment by LucianoCirino** [comment]
My unpack SDXL tuple was setup all wrong. Please try again friend.
