### ISSUE TITLE
Incompatibility between CR Multi-ControlNet Stack and Efficient Loader SDXL

### ISSUE THREAD

**Issue by alessandroperilli** [LucianoCirino/efficiency-nodes-comfyui#124]
I'm trying to load a ControlNet Stack via the Comfyroll Node, as shown below:

<img width="1139" alt="Screenshot 2023-08-31 at 14 36 49" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/ea9b0242-48ca-4c13-9d5e-060b9fb67451">

(notice that only 1 of 6 switches is on, the one about OpenPose)

I wire it into the Efficiency Loader SDXL, as shown below:

<img width="764" alt="Screenshot 2023-08-31 at 14 37 09" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/8cfb8f2d-5057-4954-a53b-b843d55e1d4e">

However, I get the following error:

`ValueError: not enough values to unpack (expected 5, got 3)`

Thank you

**Comment by LucianoCirino** [comment]
While trying to fix issue I realized that the comfyrooll cnet_stack node gives me an error on its own. Do you have this issue?

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/6a89f24b-797d-4859-a0a3-9f93c94a055a)

**Comment by Unstable-Reality** [comment]
@LucianoCirino My implementation was different, as you can see from the workflow below. It was working fine in that way.

![ComfyUI Bus Version](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/129083997/f312d099-369f-455c-9783-c12acff3a208)

**Comment by alessandroperilli** [comment]
@LucianoCirino My implementation was different, as you can see from the workflow below. It was working fine in that way.

![ComfyUI Bus Version](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/548de0ca-b73f-41ed-a937-fa9e892e5322)

**Comment by LucianoCirino** [comment]
Submitted a PR to the ComfyRoll repo regarding this issue. https://github.com/RockOfFire/ComfyUI_Comfyroll_CustomNodes/pull/15/commits/c91fcf787bc5aaf7ee02217ea37436537c09a744

**Comment by alessandroperilli** [comment]
I saw the patch merged and the Comfyroll readme.md now describing the compatibility. This is great. Thank you, @LucianoCirino
