### ISSUE TITLE
[Error][New X/Y Plot]When the calculation is completed and the final step of merging images is reached, an error occurs

### ISSUE THREAD

**Issue by Yorha4D** [LucianoCirino/efficiency-nodes-comfyui#15]
`Error occurred when executing KSampler (Efficient):

unsupported operand type(s) for *: 'int' and 'NoneType'

File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 141, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 75, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 68, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 1199, in sample
bg_width = num_cols * latent_width + (num_cols - 1) * grid_spacing + border_size_left`
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/116185401/9b1357af-82df-47e0-8642-653f5e0caad6)
When the calculation is completed and the final step of merging images is reached, an error occurs
@LucianoCirino @DrJKL

**Comment by LucianoCirino** [comment]
From the looks of the image, please load a fresh 'XY Plot' node and reconnect as needed.

**Comment by Yorha4D** [comment]
@LucianoCirino 
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/116185401/8c6c1548-bec9-4f62-a4ba-e37df9908be2)
I have found it in the temp folder now. But I still hope to have an output that can output images with descriptions to the preview node

**Comment by LucianoCirino** [comment]
I will find a way for you to do be able to do this.

**Comment by LucianoCirino** [comment]
Repo has been updated. You can now make the KSampler Efficient output the plot through the IMAGE output instead of the individual images by editing the settings on the new 'node_settings.json'.
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/88d90699-78c7-4abb-a38a-50747a10beea)

**Comment by Yorha4D** [comment]
NICE~
