### ISSUE TITLE
How to save XY plot with labels from KSampler (eff)?

### ISSUE THREAD

**Issue by sedetweiler** [LucianoCirino/efficiency-nodes-comfyui#181]
I have the grid I want, but when it saves from the KSampler it does not include the labels, just the images.  How can I save exactly what I see in the preview of the KSampler (eff)?
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/8366665/623192aa-5691-4f21-85e1-c7c0d2993634)

**Comment by LucianoCirino** [comment]
Set the ksampler output to "plot" on XY Plot node.

**Comment by sedetweiler** [comment]
Yup, just found it.  Lol.  Sorry about that.
