### ISSUE TITLE
document sampler options

### ISSUE THREAD

**Issue by halr9000** [LucianoCirino/efficiency-nodes-comfyui#185]
Sorry I know this isn't an issue but discussions aren't enabled on the repo, so unsure where else to ask, but I've got questions and the readme is pretty scant. 

What's the purpose of sampler_state = hold ?

How is vae_decode = true different from output only?

What are the tiled options for? I would expect more options to be needed for tiled sampling. (I've messed with that in auto1111, but not comfy yet).

TIA

**Comment by LucianoCirino** [comment]
I am refactoring/updating/deprecating some of these options during the next update to simplify the node.
