### ISSUE TITLE
Scalable XY Input Node.

### ISSUE THREAD

**Issue by ltdrdata** [LucianoCirino/efficiency-nodes-comfyui#19]
Would it be worth considering replacing the current dependency on multiple combos in the XY Input Node with a single multiline textbox?

This change could provide us with greater flexibility in generating XY plots.

**Comment by LucianoCirino** [comment]
That is the way I had it before, but I felt it was too complex for the regular person to setup. Maybe I can add a "Custom" XY Input node that lets you accomplish this again.

**Comment by LucianoCirino** [comment]
Repo updated. New node called 'Manual XY Entry' added under Efficiency Nodes -> XY Plot -> XY Inputs

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/dcddc4e9-8341-4991-8895-8819c25c5c92)

**Comment by ltdrdata** [comment]
> Repo updated. New node called 'Manual XY Entry' added under Efficiency Nodes -> XY Plot -> XY Inputs
> 
> ![image](https://user-images.githubusercontent.com/112517630/244977954-dcddc4e9-8341-4991-8895-8819c25c5c92.png)

It's nice. Thank you.
