### ISSUE TITLE
Multiple Loras or enabling a different Loader for XY plot node

### ISSUE THREAD

**Issue by Xiao424242** [LucianoCirino/efficiency-nodes-comfyui#20]
Hi, I would like to request a feature.

I have multi lora setup, and I would like to test other loras (157 styles) against it, with XY plot, but Efficient Loader doesn't allow for multiple Loras, and other loaders don't have the "dependencies" output. 

Would it be possible to either allow EfficientLoader to have multiple Loras or create something like a 'dependencies input node', that could be connected with basic ComfyUI nodes, to satisfy the dependencies input on the "XY Plot" node?

It would be incredibly helpful but I am not a programmer, so please excuse me, if it's an unfeasible idea.

Example:
![photobash](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/136188502/ea93727f-bc34-4749-aa6d-fb25555e69eb)

**Comment by LucianoCirino** [comment]
Although multi-LoRA chaining XY Plots would be an amazing idea to incorporate, it is a very difficult and time consuming update for me to make as of right now. I will look into it though but no promises :)

**Comment by LuposX** [comment]
Being able to use multiple loras would be awesome

**Comment by mats4d** [comment]
sadly for me it's a deal breaker as I need to use a few LORA's chained, we appreciate your work !! standing by for updates !

**Comment by LucianoCirino** [comment]
LoRA stacking is now possible via the "LoRA Stacker" node under Efficiency Nodes/Misc.
You are also able to stack LoRAs via the same node on XY Plots.
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/a8290a35-d7af-42f4-879f-08aaee7a3565" width="720">
