### ISSUE TITLE
[ControlNet] X/Y plot

### ISSUE THREAD

**Issue by seanphan** [LucianoCirino/efficiency-nodes-comfyui#27]
Hi @LucianoCirino ,

Your efficiency custom nodes helped me a lot, thanks for the great work. 

Would you consider to add ControlNet params as well?

I seem not able to find even in the manual annotation nodes.

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/5804000/f556fef2-3acc-478a-ba74-64589587070e)

<img width="313" alt="image" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/5804000/0df52134-7514-4387-ad89-c505c1a26c7a">

**Comment by LucianoCirino** [comment]
Now investigating how to achieve this. Might be a while though.

**Comment by seanphan** [comment]
Hi @LucianoCirino , thank you for revisiting this. I'm looking forward to hearing from you on this.

Some ideas (not sure if feasible) you might consider:
- Apply ControlNet (Efficient) node
- Primitive (Efficient) node -> this one is super powerful. If we can do this then just it cover major use cases.

**Comment by LucianoCirino** [comment]
@seanphan 

This is now possible with the latest Github repo updates. You can stack Control Nets via the new 'Control Net Stacker' to the 'Efficient Loader'. Also added an XY PLot Input to test varying Control Net Strengths.

![X-SRpositive Y-Checkpoints (overview)](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/f1082cf3-5df2-4e3d-8bda-43b94774c26d)

**Comment by seanphan** [comment]
This is awesome, thank you very much for your amazing works ! @LucianoCirino
