### ISSUE TITLE
"1.5 update" broke using Efficient Loader with CLIP nodes

### ISSUE THREAD

**Issue by tildebyte** [LucianoCirino/efficiency-nodes-comfyui#34]
Specifically https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/41afbf225e81bcfa0b14f8aa0066a2733a2b70cc

1) CLIP output is no longer explicitly exposed
2) I don't see any way to get the CLIP datatype out of `DEPENDENCIES`

E.g. the following pre-1.5 connection is no longer possible, and I for one use the [Advanced CLIP Text Encode](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb) nodes extensively (although I usually use better prompts than this 😝). I could load CLIP some other way, but then... what's the point of using *this* loader...
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/337875/5516435c-ea85-4e5f-98bf-716cf22fade4)

**Comment by mats4d** [comment]
Same issue here, anything with CLIP does not work, including LORAs outside of the efficiency loader, any ideas?

**Comment by tildebyte** [comment]
> Same issue here, anything with CLIP does not work, including LORAs outside of the efficiency loader, any ideas?

¯\\\_(ツ)\_/¯   I ended up having to revert to a commit from before this broke

iirc, cf90f5824ba925d84980da95105f419628e6e43d should still work (I'll try to double-check after work)

**Comment by mats4d** [comment]
Will check that, thank you so much for your work !!!

**Comment by LucianoCirino** [comment]
I have re-added the CLIP output to the Efficient Loader, please update to latest commit, and re-load node.

**Comment by tildebyte** [comment]
Fixed
