### ISSUE TITLE
X/Y plotting with sampler and scheduler 

### ISSUE THREAD

**Issue by a-essam23** [LucianoCirino/efficiency-nodes-comfyui#36]
Trying to do an X/Y plot with different samplers and schedulers does not work. Ksmapler defaults to node's scheduler.

**Comment by LucianoCirino** [comment]
Can you show me a workflow?

**Comment by a-essam23** [comment]
sorry for the very late reply
![ComfyUI_00203_](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/74434272/85bbaafa-a64f-45bc-895d-547f6d57863b)

**Comment by LucianoCirino** [comment]
I have replicated issue. Will fix asap.

**Comment by LucianoCirino** [comment]
Issue should be resolved with latest changes. Don't forget to also place a enw Efficient Loader node, since the Clip output has been re-added back in.
![XYplot](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/a7d09b81-8028-411f-9099-a34f84eaa9b1)

**Comment by a-essam23** [comment]
it's working now. thank you for your work
