### ISSUE TITLE
[Enhancement] Passing Seed Values

### ISSUE THREAD

**Issue by HaydenReeve** [LucianoCirino/efficiency-nodes-comfyui#38]
Would it be considerable to add seeds to input/output nodes here? It would make things a lot tidy when you want to control seed values across large generation maps.

**Comment by jteijema** [comment]
I think this option is already in ComfyUI.

![afbeelding](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/28191416/f5378ebc-126d-4ad6-8955-de55f337597c)


![afbeelding](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/28191416/7f4f53aa-8fc3-4950-a2c1-f8007ff9ec97)

**Comment by LucianoCirino** [comment]
What @jteijema said.

**Comment by HaydenReeve** [comment]
Apologies, let me clarify the request,

While using 'convert to input' it allows you to enter a widget node as expected.

However it does not output the seed ala the efficiency node style of input/output.

The question is more in line of "can we have a seed output" rather than a seed input.

Sorry for the confusion. 👍

**Comment by LucianoCirino** [comment]
I see. I would say no still because it would grow the node size even further which I am trying hard to avoid!

**Comment by HaydenReeve** [comment]
No stress, thanks for the consideration!
