### ISSUE TITLE
[Feature request] - Add token normalisation and interpolation from Advanced CLIP text encode

### ISSUE THREAD

**Issue by hortom** [LucianoCirino/efficiency-nodes-comfyui#4]
First, allow me to thank you for your terrific work greatly simplifying my workflow.

Recently I saw and tried the [Advanced CLIP text encode](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb) from BlenderNeko.
It has a great feature to change the token normalisation and interpolation which would be amazing to add to your Efficient Loader officially. It supports A1111, Comfy, Compel and Comfy++ interpolations - so it is easier to achieve the same result that A1111 produces, but with only 2 nodes. (I added it locally but unfortunately, I am not familiar with licences and how to start this cooperation with BlenderNeko.)
<img src="https://user-images.githubusercontent.com/1734567/233841819-2580ec39-a193-4bcd-9b0b-cdcec7985e0d.png" width="50%">

I added the 2 new params at the bottom, so no messing with the values above if Efficient Loader is already used in a workflow. They apply for both positive and negative prompts.

What do you think? Is this feasible?

**Comment by LucianoCirino** [comment]
I love the idea, I will have to also investigate how this could be achieved with the licensing. I am very new to all this aswell.

**Comment by LucianoCirino** [comment]
I messed with this a bunch yesterday and I struggled recreating Automatic1111 images even with the BlenderNeko nodes + GPU noise on KSampler. Some images were close, others not so much. I must be missing something here.

**Comment by hortom** [comment]
Honestly, I only tested the token interpolation with BlenderNeko's code in your code. It works perfectly with some specific models, e.g. Ghost Mix. The result could be different but at least, the quality is the same.
And I did nothing fancy, just added the 'adv_encode.py' file without removing unused functions and extended your code to use those. I didn't test it completely before. Comfy++ is crashing (need to figure out why), while others work. The result is: Comfy and Compel interpolations have the same results but A1111 is completely different:
|Comfy|A1111|
|---|---|
|<img src="https://user-images.githubusercontent.com/1734567/234193428-3bb884db-f33d-4c11-96d8-69e2c87be62c.png" width="95%">|<img src="https://user-images.githubusercontent.com/1734567/234193576-03461130-d2ec-4b22-b2c6-ec75978d614a.png" width="95%">|

That is good enough for me. Compfy's method lacks quality and the colours are strange.
And yes, achieving exactly the same result as A1111 is almost impossible because of the noise generation. My goal was to achieve good results with the same prompt on this particular model.
So, you extended the scope to add A1111's noise generation too. Would you like to keep that?

**Comment by LucianoCirino** [comment]
The only benefit for adding these options for me would be if you are able to actually recreate Automatic1111 images, but I just cannot with what I tested.

**Comment by hortom** [comment]
I understand. How can I help? Regardless that I am not an expert in Python, I would like to make this happen. Could you please share some problematic images so I could do some investigation on my side?

**Comment by LucianoCirino** [comment]
I used BlenderNeko's nodes with Aut1111 weight, "mean" token normalization, and did this:
https://github.com/comfyanonymous/ComfyUI/discussions/473#discussioncomment-5626147

Ans was not able to completely recreate results. The results where honestly worse than normal Aut1111.

**Comment by hortom** [comment]
Ok. If there is no (reasonably easy) way to achieve the same results as A1111 then you are right, there is no point to add extra interpolation.
