### ISSUE TITLE
Error occurred when executing XY Input: CFG Scale

### ISSUE THREAD

**Issue by jteijema** [LucianoCirino/efficiency-nodes-comfyui#47]
![afbeelding](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/28191416/234a7efd-4dec-4bb0-875c-97460d548c2d)

```Console
Error occurred when executing XY Input: CFG Scale:

TSC_XYplot_CFG.xy_value() missing 1 required positional argument: 'select_count'

  File "/home/ubuntu/ComfyUI/execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
```
Using [30a5625](https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/30a5625bf3a76e3a830253124d17a2202a65a565), the CFG Scale doesn't pass the selection count, even when it is set.

**Comment by LucianoCirino** [comment]
Can you load a new '**XY Input: CFG Scale**' node and try again please?

**Comment by jteijema** [comment]
Yeah looking through the code I can't find why my node has the field "selection_count" instead of "select_count", but I did reload the node just now, with the same result. Can nodes be cached?

**Comment by LucianoCirino** [comment]
You are not imagining things, I had changed the text from "selection_count" to "select_count" on a few XY Input nodes to make them match the rest of the XY Input nodes. Constantly changing the nodes causes saved workflows not to work but there is no other way right now to alleviate this issue.
