### ISSUE TITLE
[Feature Request] Add Lora and Hypernetwork plus CLIP textboxes to KSampler and add Hypernetworks to Loader.

### ISSUE THREAD

**Issue by vidiotgameboss** [LucianoCirino/efficiency-nodes-comfyui#5]
Support for hypernetworks has been added to ComfyUI as of 12 hours ago so this is now possible.
The efficient KSampler would benefit from having lora and hypernetwork strengths added along with the clip textboxes because that would result in being able to use less nodes when doing multiple sampling stages (most basic being 2 step like HiRes) in which you might want to condition CLIP differently and set different lora/hypernetwork strengths, or perhaps even load additional LORAs further into the sampling.

I assume this should be doable as it's nothing new, rather it would just be features from the Efficient Loader moved over to the KSampler.

**Comment by vidiotgameboss** [comment]
Additionally, if it is possible, VAE decoding with preview replacing the current preview_image in KSampler. That way we would get a step by step live preview as the image is being decoded.

**Comment by vidiotgameboss** [comment]
thought to try my hand at editing the current nodes, ive got it done and now im gonna try adding hypernetworks to both the ksampler and the loader
![WIP](https://user-images.githubusercontent.com/63921540/234124032-7fb46778-2918-4be2-9912-7a85a61f7ef4.png)

**Comment by LucianoCirino** [comment]
> Additionally, if it is possible, VAE decoding with preview replacing the current preview_image in KSampler. That way we would get a step by step live preview as the image is being generated instead of just a final result.

Wouldn't this slow down generation? having to decode latent between steps?

I am not sure I like the idea of making the KSampler Efficient node bigger than it already is...

**Comment by vidiotgameboss** [comment]
> > Additionally, if it is possible, VAE decoding with preview replacing the current preview_image in KSampler. That way we would get a step by step live preview as the image is being generated instead of just a final result.
> 
> Wouldn't this slow down generation? having to decode latent between steps?
> 
> I am not sure I like the idea of making the KSampler Efficient node bigger than it already is...

it does slow it down slightly but gaining the ability to use prompt editing (once it'll be implemented) is worth it, maybe have preview_image have 3 options: Disabled, Result (which would be current implementation) and Live (which would be a live preview), that way people who dont want to use it dont have to
