### ISSUE TITLE
LoRA stacker -> Efficient Loader dont work

### ISSUE THREAD

**Issue by tudal** [LucianoCirino/efficiency-nodes-comfyui#57]
im trying to use lora with LoRA stacker connected to Efficient Loader and seems like it just dont work
when I set lora inside Efficient Loader its all good

**Comment by tudal** [comment]
Ok so it doesn't work if Efficient Loader dont have any lora

**Comment by LucianoCirino** [comment]
I will change this behavior to work as you expect during one of the next updates. Thanks for the input.

**Comment by Mijago** [comment]
This should actually be solved with #55, no?

**Comment by LucianoCirino** [comment]
> This should actually be solved with #55, no?

Correct 👍

**Comment by LucianoCirino** [comment]
This item is now complete.
