### ISSUE TITLE
Weird image/preview output

### ISSUE THREAD

**Issue by gobshyte** [LucianoCirino/efficiency-nodes-comfyui#58]
I just tested attaching Efficient Loader to KSampler (Efficient) , then image ouput linked to a save image node and a preview image node. No loras, connected all the KSample inputs except script.

If I leave preview_image as disabled - I still get a preview in the KSampler (Efficient), but the preview image node shows nothing, the save image shows nothing, and it saves a 1x1 pixel image!

If I enable preview_image, I get 2 previews of the same image in KSampler (Efficient), the preview image node shows a preview, but the save image node is empty. It does actually save the image in this case though...

I've got a nuch of other custom nodes so perhaps it's a conflict, any ideas? 

ComfyUI-Impact-Pack
ComfyUI_Comfyroll_CustomNodes
ComfyUI_SeeCoder
ComfyUI_UltimateSDUpscale
comfy_controlnet_preprocessors
Derfuu_ComfyUI_ModdedNodes
efficiency-nodes-comfyui
images-grid-comfy-plugin
masquerade-nodes-comfyui
SeargeSDXL
was-node-suite-comfyui

**Comment by LucianoCirino** [comment]
>If I leave preview_image as disabled - I still get a preview in the KSampler (Efficient), but the preview image node shows nothing, the save image shows nothing, and it saves a 1x1 pixel image!

The saving of a 1x1 pixel image when the preview is disabled is not really an unintended behavior but a result of being forced to return an image from the 'IMAGE' output so downstream nodes connected to this output don't generate errors.

Below is the return code for the 'Ksampler Efficient' when preview_image is Disabled.

```
empty_image = pil2tensor(Image.new('RGBA', (1, 1), (0, 0, 0, 0)))
# ...
            # If not in preview mode, return the results in the specified format
            if preview_image == "Disabled":
                # Enable vae decode on next Hold
                update_value_by_id("vae_decode", my_unique_id, True)
                return {"ui": {"images": list()},
                        "result": (model, positive, negative, {"samples": latent}, vae, TSC_KSampler.empty_image,)}
```

Notice I return a 1x1 RGBA image as my "empty".

>If I enable preview_image, **I get 2 previews of the same image in KSampler (Efficient)**, the preview image node shows a preview, but the save image node is empty. It does actually save the image in this case though...

 This issue I am not totally sure, could you provide a workflow so I can test it from my end?

**Comment by LucianoCirino** [comment]
I was able tor eplicate this issue. It happens with the ComfyUI managers live preview viewer. Will investigate.
