### ISSUE TITLE
Cannot unpack non-iterable CLIP object

### ISSUE THREAD

**Issue by gobshyte** [LucianoCirino/efficiency-nodes-comfyui#59]
Trying to run the example XY plot, I just swapped out models, and swapped from a XY model to an XY steps, and I can't get it to work, I keep getting error:

cannot unpack non-iterable CLIP object

Might be another conflict as per previous issue I just posted?? (but unsure)

I've attached workflow (I think?!)

[cannot unpack non-iterable CLIP object.json.txt](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12165011/cannot.unpack.non-iterable.CLIP.object.json.txt)

Error in GUI:

Error occurred when executing KSampler (Efficient):

cannot unpack non-iterable CLIP object

  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 806, in sample
    vae_name, ckpt_name, clip, clip_skip, positive_prompt, negative_prompt,\
Queue size: 0
Extra options

In console:

got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\SDAI\ComfyUI\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 806, in sample
    vae_name, ckpt_name, clip, clip_skip, positive_prompt, negative_prompt,\
TypeError: cannot unpack non-iterable CLIP object

**Comment by gobshyte** [comment]
I just got some updates on a pull - will retest

**Comment by gobshyte** [comment]
Ah no :( still same error

**Comment by LucianoCirino** [comment]
Not home, but just looking through your Json it looks like you need to Load a new Efficient Loader. Follow these steps:

1) Load a new Efficient Loader from nodes menu in ComfyUI
2) Copy over settings from the old Efficient Loader by right clicking the old Efficient Loader node , select "copy clipspace", and paste it to the new Efficient Loader node. Manually change whatever settings don't get copied over.
3) Delete old Efficient Loader
4) Connect New Efficient Loader

**Comment by gobshyte** [comment]
OK that seemed to do the trick, thanks. I think I was using the json from this png though, so you might want to update it?
https://github.com/LucianoCirino/efficiency-nodes-comfyui/blob/main/workflows/XYplot/X-Seeds%20Y-Checkpoints%20(overview).png
