### ISSUE TITLE
Can not use negative values in XY Input: Manual XY Entry

### ISSUE THREAD

**Issue by bytecann** [LucianoCirino/efficiency-nodes-comfyui#60]
I tried the manual scrip node for x/z/y plot, and it works fine, except went wanting to use negative values…it gives "XY Plot Error" -1.0 is not valid strength number must be between 0 and 10... BUT... If I use the XY Input: LoRA Adv node, then negative values like -1 or -0.9 work fine… Any idea what the issue is ?
![XYZ-Plot Error](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/138059263/c8b8ebef-460a-492e-8a3e-9e8c83863ee8)

**Comment by LucianoCirino** [comment]
This was a mistake on my part, updated repo. This should now be fixed by latest comit: https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/29f7cfc5c6ce68bd3429bf0cb40b19b7ce2da00a

**Comment by bytecann** [comment]
Thank you for sorting that out.
