### ISSUE TITLE
Prompt S/R does not operate in XY Plot when Controlnet is applied.

### ISSUE THREAD

**Issue by mongpic** [LucianoCirino/efficiency-nodes-comfyui#62]
Prompt S/R does not operate in XY Plot when Controlnet is applied.

<img width="1048" alt="Prompt_sr_Controlnet" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/20902086/d3c99c8b-0b9f-4ad2-9587-1b40cf241104">

I haven't tested all of them, but the controlnet works for things like CFG.
<img width="1061" alt="Prompt_sr_Controlnet2" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/20902086/4044fff6-7126-4997-9938-ed33a48d7121">

**Comment by LucianoCirino** [comment]
Currently Control Net is not supported for XY Plots, I will eventually have an update where this will be available.

**Comment by mongpic** [comment]
Thanks for the answer. I hope it will be updated

**Comment by LucianoCirino** [comment]
This is now possible with the latest Github repo updates
![X-SRpositive Y-Checkpoints (overview)](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/f1082cf3-5df2-4e3d-8bda-43b94774c26d)

**Comment by mongpic** [comment]
This was a really needed feature, thank you so much. Bless you.
