### ISSUE TITLE
Efficient Loader ignoring SDXL LORAs ?

### ISSUE THREAD

**Issue by isamarsh** [LucianoCirino/efficiency-nodes-comfyui#65]
I'm trying to use the Offset LORA that comes with SDXL and it is not picked up at all. No errors, it just acts as if it isn't present. I've also tried plugging in a LORA stack node and the LORA gets ignored there as well.

**Comment by LucianoCirino** [comment]
This issue should now be resolved by commit https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/50a95c5f926c81e81b03d5a74bf64594d6b587ea. Please update to latest version and try again.

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/ab3615e0-1af4-46a5-8084-eb1d07c7e443)

**Comment by isamarsh** [comment]
Thanks you, this is working fine now !
