### ISSUE TITLE
Efficiency node not avail in the contextual menu

### ISSUE THREAD

**Issue by visjble** [LucianoCirino/efficiency-nodes-comfyui#72]
Hi, I did install this node using the comfy mngr. I see the correct folder inside the custom_nodes as expected. however, under the menu Add node-sampling> there are only the defaul
![Capture](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/8854071/9f8f65a7-a843-4976-8559-eccf58755e4a)
ts, see pic. Refreshed, restarted, checked for missing etc...

**Comment by LucianoCirino** [comment]
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/b2b06ff6-5e8f-4533-aa13-ed7261054dd3)
:)

**Comment by visjble** [comment]
Doh, I came here to remove my post because I found it....
