### ISSUE TITLE
With the last update i have IMPORT FAILED: No module named 'websockets'

### ISSUE THREAD

**Issue by lellotrek** [LucianoCirino/efficiency-nodes-comfyui#78]
First of all thank you for your work.
Like i wrote from the last update i receive import failed error with this specification:
 File "E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 43, in <module>
    from tsc_utils import *
  File "E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 500, in <module>
    import websockets #https://github.com/python-websockets/websockets
ModuleNotFoundError: No module named 'websockets'

Cannot import E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: No module named 'websockets'

Of course i update to the last version the Comfyui this morning too.

**Comment by LucianoCirino** [comment]
Hello @lellotrek. The most recent updates require the Python pip "websockets" to be installed. I have the package attempt to auto install this package but it must have failed. Please install the dependencies and try again.
https://github.com/LucianoCirino/efficiency-nodes-comfyui/blob/main/requirements.txt

pip install websockets

**Comment by lellotrek** [comment]
Grazie Luciano but even using the command ( your folder/cmd) i receive this message out:

E:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui>pip install websockets
Requirement already satisfied: websockets in c:\users\notelello\appdata\roaming\python\python310\site-packages (11.0.3)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Deleted and installing the nodes not fix the issue too

**Comment by LucianoCirino** [comment]
@lellotrek try this.

**pip install websockets simpleeval --target="E:\AI\ComfyUI\python_embeded\Lib\site-packages"**


If this works I will update my auto package installer to find the ComfyUI packages by reference.

**Comment by lellotrek** [comment]
It's working Luciano. 
Thanks and again thanks for your work and help.

**Comment by LucianoCirino** [comment]
In reference to this issue, I have updated how the auto-package installer imports the requirements.

https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/1b882e0f11959b19b8c1021b2c6aae0250f4bbd8
