### ISSUE TITLE
[Bug] External seed input causes type error

### ISSUE THREAD

**Issue by TinyTerra** [LucianoCirino/efficiency-nodes-comfyui#8]
Using an external node (i.e not a primitive) as the seed input of a KSampler (Efficient) node throws a typeError;

>Traceback (most recent call last):
  File "T:\AI\Comfy\ComfyUI\execution.py", line 183, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "T:\AI\Comfy\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "T:\AI\Comfy\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 433, in sample
    last_results = get_value_by_id("results", my_unique_id)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

The only thing I can see changing is inside the prompt input - Sampler_state, 'seed' is a reference to a node instead of an integer.

This version of the prompt input works:
> prompt:  {'1': {'inputs': {'ckpt_name': 'Good\\deliberate_v2.safetensors', 'vae_name': 'vae-ft-mse-840000-ema-pruned.safetensors', 'clip_skip': -1, 'lora_name': 'None', 'lora_model_strength': 1.0, 'lora_clip_strength': 1.0, 'positive': 'cat', 'negative': 'dog', 'empty_latent_width': 512, 'empty_latent_height': 512, 'batch_size': 1}, 'class_type': 'Efficient Loader'}, '23': {'inputs': {'sampler_state': 'Sample', 'seed': 819386554663363, 'steps': 3, 'cfg': 8.0, 'sampler_name': 'euler', 'scheduler': 'karras', 'denoise': 1.0, 'preview_image': 'Enabled', 'model': ['1', 0], 'positive': ['1', 1], 'negative': ['1', 2], 'latent_image': ['1', 3], 'optional_vae': ['1', 4]}, 'class_type': 'KSampler (Efficient)'}, '28': {'inputs': {'model': ['1', 0], 'pos': ['1', 1], 'neg': ['1', 2], 'latent': ['1', 3], 'vae': ['1', 4]}, 'class_type': 't Pipe IN t'}, '29': {'inputs': {'pipe': ['28', 0]}, 'class_type': 't Pipe OUT t'}}

and this one doesn't:
>prompt:  {'1': {'inputs': {'ckpt_name': 'Good\\deliberate_v2.safetensors', 'vae_name': 'vae-ft-mse-840000-ema-pruned.safetensors', 'clip_skip': -1, 'lora_name': 'None', 'lora_model_strength': 1.0, 'lora_clip_strength': 1.0, 'positive': 'cat', 'negative': 'dog', 'empty_latent_width': 512, 'empty_latent_height': 512, 'batch_size': 1}, 'class_type': 'Efficient Loader'}, '23': {'inputs': {'sampler_state': 'Sample', 'seed': ['29', 6], 'steps': 3, 'cfg': 8.0, 'sampler_name': 'euler', 'scheduler': 'karras', 'denoise': 1.0, 'preview_image': 'Enabled', 'model': ['1', 0], 'positive': ['1', 1], 'negative': ['1', 2], 'latent_image': ['1', 3], 'optional_vae': ['1', 4]}, 'class_type': 'KSampler (Efficient)'}, '28': {'inputs': {'seed': 819386554663363, 'model': ['1', 0], 'pos': ['1', 1], 'neg': ['1', 2], 'latent': ['1', 3], 'vae': ['1', 4]}, 'class_type': 't Pipe IN t'}, '29': {'inputs': {'pipe': ['28', 0]}, 'class_type': 't Pipe OUT t'}}

**Comment by LucianoCirino** [comment]
I think I know why this is happening. Will look into it, thanks.

**Comment by LucianoCirino** [comment]
Please grab the latest changes from the Github repo. Should be fixed now!

**Comment by TinyTerra** [comment]
Cheers 👍
